import Link from "next/link";
import { ArrowRight, Check, FileText, Quote } from "lucide-react";
import { guides, trust } from "@/lib/content";

export default function Home() {
  return <>
    <section className="hero">
      <div className="container hero-grid">
        <div><span className="eyebrow">Independent customer experiences & business setup awareness</span><h1>Before you choose a business setup consultant, <em>know the full story.</em></h1><p className="lede">This independent platform shares documented customer experiences and practical lessons to help entrepreneurs make informed decisions.</p><div className="actions"><Link className="button" href="/our-experience">Read the documented experience <ArrowRight size={17}/></Link><Link className="button button-ghost" href="/submit-experience">Share your experience</Link></div><p className="fineprint"><Check size={15}/> Content is based on firsthand accounts and supporting records where available.</p></div>
        <aside className="case-card"><div className="case-card-top"><span>Featured experience</span><span className="pill green">Open for response</span></div><Quote size={26}/><h2>A customer experience worth understanding</h2><p>The parties appear to disagree about the timing of an outstanding payment and the actions that could follow.</p><dl><div><dt>Discussed total</dt><dd>AED 12,000</dd></div><div><dt>Initial amount paid</dt><dd>AED 5,700</dd></div><div><dt>Remaining balance</dt><dd>AED 6,300</dd></div></dl><Link href="/our-experience">View the full, attributed account <ArrowRight size={16}/></Link></aside>
      </div>
    </section>
    <section className="trust-strip"><div className="container four-grid">{trust.map(({title,text,icon:Icon}) => <article key={title}><Icon/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="section"><div className="container"><div className="section-head split"><div><span className="eyebrow">The featured experience</span><h2>What the parties appear to disagree about</h2></div><p>Careful attribution matters. This platform does not independently determine legal liability.</p></div><div className="statement-grid"><article className="statement"><span className="label amber">Customer account</span><p>“The customer states that a business setup process began after an initial payment of AED 5,700 against a discussed total of AED 12,000.”</p></article><article className="statement"><span className="label navy">Company position</span><p>The company states that its payment terms and consequences were communicated and that it acted according to the agreed process.</p></article></div><div className="center"><Link className="text-link" href="/timeline">View full timeline and evidence <ArrowRight size={16}/></Link></div></div></section>
    <section className="section tinted"><div className="container split-feature"><div><span className="eyebrow">Why this platform exists</span><h2>Clarity before commitment.</h2><p className="lede small">Better outcomes begin with clear written agreements, transparent payment terms and proper notice before major action.</p><Link className="button button-dark" href="/about">Read our editorial principles</Link></div><ul className="check-list">{["Confirm payment extensions in writing","Understand who controls each application","Request refund and deduction policies before paying","Keep emails, receipts and agreements together","Ask what follows if payment terms change"].map(x=><li key={x}><Check/>{x}</li>)}</ul></div></section>
    <section className="section"><div className="container"><div className="section-head split"><div><span className="eyebrow">Awareness guides</span><h2>Practical reading before you sign.</h2></div><Link className="text-link" href="/guides">Browse all guides <ArrowRight size={16}/></Link></div><div className="guide-grid">{guides.slice(0,3).map(([title,cat,time],i)=><Link href={`/guides/${slug(title)}`} className="guide-card" key={title}><span className="guide-number">0{i+1}</span><span className="eyebrow">{cat}</span><h3>{title}</h3><span>{time} read <ArrowRight size={15}/></span></Link>)}</div></div></section>
    <section className="section"><div className="container response-panel"><div><FileText/><span className="eyebrow">A fair right of response</span><h2>Every business deserves space to respond.</h2><p>Businesses mentioned may submit a response, correction, clarification or supporting document. Approved responses are displayed prominently and without unfair alteration.</p></div><Link className="button button-light" href="/company-response">Submit a company response</Link></div></section>
    <section className="section compact"><div className="container disclosure"><strong>Share a genuine experience</strong><p>Submissions are reviewed before publication. Unsupported accusations, abusive content, private personal data and unverifiable claims may be rejected or edited.</p><Link className="button" href="/submit-experience">Start a secure submission</Link></div></section>
  </>;
}
function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
